apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dabones/gitops-demo.git
        revision: HEAD
        directories:
          - path: apps/*
    - list:
        elements:
          - env: dev
            path: apps/dev
          - env: staging
            path: apps/staging
          - env: prod
            path: apps/prod
  template:
    metadata:
      name: '{{path.basename}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/dabones/gitops-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true